import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/ui/Sidebar";

import ReactQueryProvider from "@/lib/providers/ReactQueryProvider";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex overflow-x-hidden bg-[#c9d6e3] transition-colors duration-300">
        <AuthProvider>
          <ReactQueryProvider>
            <SideBar />
            <div className="w-full min-h-screen bg-[#c9d6e3] p-4 md:p-8 ml-0 md:ml-64 pt-16 md:pt-8 overflow-x-hidden">
              {children}
            </div>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
